### ISSUE TITLE
File Browser Command throws an error

### ISSUE THREAD

**Issue by lyndhurst** [LarsHaalck/wiki.nvim#1]
Hi,
I have the "notes directory" properly configured, and all mappings / commands are working fine except for the `browser` telescope extension.

Issuing `lua require('telescope').extensions.wiki.browser()` throws the following error:

```
E5108: Error executing lua .../site/pack/packer/start/wiki.nvim/lua/wiki/telescope.lua:142: attempt to call field 'file_browser' (a nil value)                        
stack traceback:
        .../site/pack/packer/start/wiki.nvim/lua/wiki/telescope.lua:142: in function 'browser'
        [string ":lua"]:1: in main chunk
```

Checking line 142, it looks like  only cwd is expected... On my side, I have no special configuration for the `file_browser` builtin in telescope, and it is working fine when I call it. In am using nvim 0.8.0 and everything is up to date.

Thank you for your help.

**Comment by LarsHaalck** [comment]
Thanks, I missed that telescope moved the filebrowser into a separate repo. I fixed it (you probably want to install it first https://github.com/nvim-telescope/telescope-file-browser.nvim)
